const fs = require('fs');
let s = fs.readFileSync('D:/1kaifa/grsds/index.html', 'utf8');
console.log('Start size:', s.length);

// ============================================
// FIX 1: workflows tab — load allRoles/allDepartments first
// ============================================
let wfOld = "else if(tab==='workflows'){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');renderWorkflowTemplates();}";
let wfNew = "else if(tab==='workflows'){(async function(){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');if(!allRoles||!allRoles.length||!allDepartments||!allDepartments.length)await loadAdminData();renderWorkflowTemplates();})();}";
if (s.includes(wfOld)) {
  s = s.replace(wfOld, wfNew);
  console.log('FIX1 (workflows tab): OK');
} else {
  console.log('FIX1: NOT FOUND, search around');
  let i = s.indexOf("tab==='workflows'");
  if (i > 0) console.log('near:', s.slice(i, i+250));
}

// ============================================
// FIX 2: wfSetAssignee(2, → wfSetAssignee('+idx+',
// ============================================
// The raw bytes in the file: wfSetAssignee(2,\'value\',this.value)
// Use simple string replace
let pat2 = "wfSetAssignee(2,\\'value\\',this.value)";
let rep2 = "wfSetAssignee('+idx+','value',this.value)";
// We need to keep the backslashes since they escape the quotes in the JS source.
// Wait - the file has literal: wfSetAssignee(2,\'value\',this.value)
// In the JS source, that means wfSetAssignee(2, 'value', this.value)
// To change 2 to '+idx+', we just need: wfSetAssignee('+idx+','value',this.value)
// In a Node string: "wfSetAssignee('+idx+','value',this.value)" — this is the raw text we want
let pat2b = "wfSetAssignee(2,'value',this.value)";  // 2 is already a number, not a string
// But the file has: wfSetAssignee(2,\'value\',this.value) — the \' are escape sequences in JS
// In raw file bytes, that's literally: w,f,S,e,t,A,s,s,i,g,n,e,e,(,2,,,\,',v,a,l,u,e,\,',,,t,h,i,s,.,v,a,l,u,e,)
// So the JS string delimiter in this raw text is ' (single quote)
// And inside, \' represents a single quote character
// To change 2 to '+idx+', I just replace 2 with '+idx+'
// But the surrounding is: wfSetAssignee(2,\'value\',this.value)
// This is INSIDE a JS string, so it's already escaped. The raw text in the file:
//   wfSetAssignee(2,\'value\',this.value)
// I want raw text:
//   wfSetAssignee('+idx+','value',this.value)
// So in Node: "wfSetAssignee(2,\\'value\\',this.value)" → "wfSetAssignee('+idx+','value',this.value)"
// Wait the file uses \' to escape, not \\'.
// Actually the file is HTML containing JS. The JS source has: 
//   h+='<select onchange="wfSetAssignee(2,\'value\',this.value)">...';
// In the actual file bytes: the onchange attribute value uses double quotes "...",
// so the inner single quotes don't need escaping, but they break the outer JS string.
// So the file actually has: wfSetAssignee(2,\'value\',this.value)
// In the raw file: the chars are w,f,S,e,t,A,s,s,i,g,n,e,e,(,2,,,\,',v,a,l,u,e,\,',...
// So the Node string for the search: "wfSetAssignee(2,\\'value\\',this.value)" — yes that's right
// Wait, in Node: '\\' produces a single \ in the string, and '' produces a single '
// So "wfSetAssignee(2,\\'value\\',this.value)" produces: wfSetAssignee(2,\'value\',this.value)
// YES! That matches.
// To produce the desired: wfSetAssignee('+idx+','value',this.value)
// In Node: "wfSetAssignee('+idx+','value',this.value)"
// Notice: the +idx+ is concatenated in JS, so the +'s don't need escaping in Node string
// But the ' around value... we want them to be literal 's in the file. The desired file content
// has 'value' with single quotes. In Node string: "wfSetAssignee('+idx+','value',this.value)"
// produces: wfSetAssignee('+idx+','value',this.value)
// That's what we want.

s = s.replace("wfSetAssignee(2,\\'value\\',this.value)", "wfSetAssignee('+idx+','value',this.value)");
console.log('FIX2 (assignee idx):', s.indexOf("wfSetAssignee(2,") < 0 ? 'OK' : 'STILL THERE');

// ============================================
// FIX 3: staff dropdown — bare HTML attributes
// ============================================
// Find the staff section in wfShowProps
// Old: h+='<label>鎸囧畾鍛樺伐</label><select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>鏃?/option>';
// The h+=' part is generated by JS. The issue is the generated HTML has bare attrs.
let old3a = "<select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>";
let new3a = '<select id="wf-staff-dd-\''+idx+'\'" onchange="wfSetAssignee('+idx+',\'staffId\',this.value)"><option value="">';
// In raw file bytes:
// OLD: <select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>
// Wait, "staffId" needs to be a string in the generated HTML's onchange attribute
// If we want the generated HTML to be: onchange="wfSetAssignee(NN,'staffId',this.value)"
// then in the JS source, the string we build is: "wfSetAssignee('+idx+','staffId',this.value)"
// In the raw JS source, this is written as: h+='<...onchange="wfSetAssignee('+idx+',\'staffId\',this.value)">...'
// The outer ' is the JS string delimiter. Inside, we use \' for literal '.
// So in the raw file: ...onchange="wfSetAssignee('+idx+',\'staffId\',this.value)"...
// The \ in the file means literal escape in JS source. Good.
// So: old raw = <select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>
// new raw = <select id="wf-staff-dd-'+idx+'" onchange="wfSetAssignee('+idx+',\'staffId\',this.value)"><option value="">
// In Node string:
// OLD: "<select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>"
// NEW: '<select id="wf-staff-dd-\''+idx+'\'" onchange="wfSetAssignee('+idx+',\'staffId\',this.value)"><option value="">'

s = s.replace("<select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>", '<select id="wf-staff-dd-\''+idx+'\'" onchange="wfSetAssignee('+idx+',\'staffId\',this.value)"><option value="">');
console.log('FIX3a (staff select):', s.includes('id="wf-staff-dd-\'') ? 'OK' : 'STILL BROKEN');

// Also fix: h+='<option value='+escHtml → h+='<option value="'+escHtml
let old3b = "h+='<option value='+escHtml(allUsers[ui].user_id)+\"";
let new3b = 'h+=\'<option value="\'+escHtml(allUsers[ui].user_id)+\"';
// In raw file: h+='<option value='+escHtml(allUsers[ui].user_id)+''+(...
// In Node: "h+='<option value='+escHtml(allUsers[ui].user_id)+\"" — the +" in raw means +' (closing JS string then quote then concat)
// Wait, I need to be careful. Let me use chr codes
let rawOld3b = "h+='<option value='+escHtml(allUsers[ui].user_id)+'";
// Desired: h+='<option value="'+escHtml(allUsers[ui].user_id)+'
// In Node: "h+='<option value=\"'+escHtml(allUsers[ui].user_id)+'"
s = s.replace("h+='<option value='+escHtml(allUsers[ui].user_id)+'", 'h+=\'<option value="\'+escHtml(allUsers[ui].user_id)+\'');
console.log('FIX3b (option value quotes):', s.includes('h+=\'<option value="\'+escHtml') ? 'OK' : 'check');

// ============================================
// FIX 4: doCheckIn → setTimeout hard timeout + doSaveCheckIn
// ============================================
let gps = fs.readFileSync('D:/1kaifa/grsds/_gps_new.txt', 'utf8').trim();
let dc = s.indexOf('async function doCheckIn(type){');
let ov = s.indexOf('\nfunction openVisitForm', dc);
if (dc > 0 && ov > dc) {
  s = s.slice(0, dc) + gps + '\n' + s.slice(ov);
  console.log('FIX4 (GPS): OK, replaced', ov-dc, 'bytes with', gps.length);
}

fs.writeFileSync('D:/1kaifa/grsds/index.html', s, 'utf8');
console.log('Final size:', s.length);

// Verify
let ls = s.lastIndexOf('<script>'), le = s.lastIndexOf('</script>');
try { new (require('vm').Script)(s.slice(ls+8, le)); console.log('JS: OK'); }
catch(e) { 
  console.log('JS FAIL:', e.message.substring(0,200)); 
  let m = e.stack ? e.stack.match(/inline:(\d+)/) : null;
  if (m) {
    let ln = parseInt(m[1]);
    let lines = s.slice(ls+8, le).split('\n');
    for (let k = Math.max(0,ln-3); k < Math.min(lines.length, ln+2); k++)
      console.log('L'+(k+1)+': '+(lines[k]||'').substring(0,200));
  }
}
let o=(s.match(/<div[\s>]/g)||[]).length, c=(s.match(/<\/div>/g)||[]).length;
console.log('Div:',o,c,o-c);
