const fs = require('fs');
let s = fs.readFileSync('D:/1kaifa/grsds/index.html', 'utf8');

// === BUG 1: GPS - use watchPosition (more reliable on mobile) with hard timeout ===
let dcStart = s.indexOf('async function doCheckIn(type){\n');
if (dcStart > 0) {
  // Find end of doCheckIn (before \nasync function loadFWVisits or \nfunction loadFWTrack)
  let dcEnd = s.indexOf('\nasync function loadFWVisits', dcStart);
  if (dcEnd < 0) dcEnd = s.indexOf('\nfunction loadFWTrack', dcStart);
  if (dcEnd > 0) {
    let oldFn = s.slice(dcStart, dcEnd);
    console.log('doCheckIn found, length:', oldFn.length);

    let newFn = `async function doCheckIn(type){
  var note=document.getElementById('fw-checkin-note').value.trim();
  var addr='';
  var label=type==='in'?'上班签到':'下班签退';
  var btnEl=type==='in'?document.getElementById('fw-btn-in'):document.getElementById('fw-btn-out');
  btnEl.disabled=true;btnEl.textContent='获取定位中...';
  var settled=false;
  var cleanup=function(){settled=true;btnEl.disabled=false;btnEl.textContent=type==='in'?'📍 上班签到':'🏠 下班签退'};

  // Hardware timer: always fires after 8s max
  var hardTimer=setTimeout(function(){
    if(!settled){cleanup();showToast('⚠️ 定位超时(8秒)，无定位签到中...');doCheckInNoGPS(type,note,addr,label);}
  },8000);

  if(!navigator||!navigator.geolocation){
    clearTimeout(hardTimer);cleanup();showToast('⚠️ 浏览器不支持定位');return;
  }

  // Try getCurrentPosition - if browser hangs, hardTimer saves us
  navigator.geolocation.getCurrentPosition(
    function(pos){
      if(settled)return;
      var lat=pos.coords.latitude,lng=pos.coords.longitude;
      if(isNaN(lat)||isNaN(lng)){if(!settled){clearTimeout(hardTimer);cleanup();showToast('⚠️ 坐标无效，无定位签到中...');doCheckInNoGPS(type,note,addr,label);}return;}
      clearTimeout(hardTimer);
      cleanup();
      window._fwPendingType=type;
      showLocationConfirm(lat,lng,type==='in'?'📍 上班签到 - 确认位置':'🏠 下班签退 - 确认位置',async function(clat,clng){
        window._fwPendingType=null;
        btnEl.disabled=true;btnEl.textContent='保存中...';
        try{
          var r=await sb.from('field_checkins').insert({user_id:currentUser.id,type:type,latitude:clat,longitude:clng,address:addr,note:note||null,company_id:currentCompanyId}).select();
          btnEl.disabled=false;btnEl.textContent=type==='in'?'📍 上班签到':'🏠 下班签退';
          if(r.error){showToast(label+'失败: '+r.error.message);return}
          showToast(type==='in'?'✅ 签到成功！':'🏠 签退成功，辛苦了！');
          document.getElementById('fw-checkin-note').value='';
          loadFWCheckin();loadFWOverview();
        }catch(e){btnEl.disabled=false;btnEl.textContent=type==='in'?'📍 上班签到':'🏠 下班签退';showToast(label+'失败: '+(e.message||e));console.error(e)}
      });
    },
    function(err){
      if(settled)return;
      clearTimeout(hardTimer);
      cleanup();
      if(err.code===1)showToast('⚠️ 定位被拒绝，无定位签到中...');
      else showToast('⚠️ GPS不可用，无定位签到中...');
      doCheckInNoGPS(type,note,addr,label);
    },
    {timeout:7000,enableHighAccuracy:true,maximumAge:60000}
  );
}

async function doCheckInNoGPS(type,note,addr,label){
  var btnEl=type==='in'?document.getElementById('fw-btn-in'):document.getElementById('fw-btn-out');
  try{
    var r=await sb.from('field_checkins').insert({user_id:currentUser.id,type:type,latitude:null,longitude:null,address:addr,note:note||null,company_id:currentCompanyId}).select();
    btnEl.disabled=false;btnEl.textContent=type==='in'?'📍 上班签到':'🏠 下班签退';
    if(r.error){showToast(label+'失败: '+r.error.message);return}
    showToast(type==='in'?'✅ 签到成功！（无定位）':'🏠 签退成功！（无定位）');
    document.getElementById('fw-checkin-note').value='';
    loadFWCheckin();loadFWOverview();
  }catch(e){btnEl.disabled=false;btnEl.textContent=type==='in'?'📍 上班签到':'🏠 下班签退';showToast(label+'失败: '+(e.message||e));console.error(e)}
}`;
    s = s.slice(0, dcStart) + newFn + s.slice(dcEnd);
    console.log('BUG 1 (GPS): replaced, new fn length:', newFn.length);
  }
}

// === BUG 3: staffId missing quotes in wfShowProps ===
// Find the raw string fragment: wfSetAssignee('+idx+',staffId,this.value)
// This is embedded in JS concatenation so in the HTML file it's literal text
let staffPat = /wfSetAssignee\('\+idx\+',staffId,/g;
let staffCnt = 0;
s = s.replace(staffPat, function() { staffCnt++; return "wfSetAssignee('+idx+','staffId',"; });
console.log('BUG 3 (staffId):', staffCnt, 'replacements');

// Also fix missing quotes in HTML attributes generated by wfShowProps
// id=wf-staff-dd-'+idx+' → id="wf-staff-dd-'+idx+'"
// onchange="wfSetAssignee(...)" → already has quotes from _fix_wf_staff2.cjs, but staffId was raw
// Actually the id= and onchange= in the wfShowProps function are inside JS string concat,
// the issue is the rendered HTML output. Let's check what was generated.
// The wf-staff-dd select is created by: h+='<select id=wf-staff-dd-'+idx+' onchange=...
// These need quotes around the attribute values

// Fix the id= attribute in the staff dropdown
s = s.replace(/id=wf-staff-dd-\+idx\+/g, 'id="wf-staff-dd-\'+idx+\'"');
console.log('staff-dd id quotes:', s.match(/id="wf-staff-dd/g) ? s.match(/id="wf-staff-dd/g).length : 0);

// Fix the onchange= attribute  
s = s.replace(/onchange=wfSetAssignee\('\+\w+\+','staffId',/g, function(m) { return m.replace('onchange=','onchange="').replace(",'staffId',", ',staffId,'); });
// Hmm this is getting complex. Let me just fix the specific pattern in the file.
// The original is: h+='<select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)>
// After our fix the staffId has quotes but the HTML attributes id= and onchange= still lack quotes

// Let's find what we actually have now
let testIdx = s.indexOf('wf-staff-dd-');
while (testIdx > 0) {
  let frag = s.slice(testIdx, testIdx + 120);
  console.log('staff-dd frag:', JSON.stringify(frag.substring(0, 80)));
  testIdx = s.indexOf('wf-staff-dd-', testIdx + 50);
  if (testIdx > testIdx + 100000) break;
}

// === BUG 2: workflows tab needs loadAdminData ===
let swOld = "else if(tab==='workflows'){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');renderWorkflowTemplates();}";
let swNew = "else if(tab==='workflows'){(async function(){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');if(!allRoles||!allRoles.length)await loadAdminData();if(!allDepartments||!allDepartments.length)await loadAdminData();renderWorkflowTemplates();})();}";
if (s.includes(swOld)) {
  s = s.replace(swOld, swNew);
  console.log('BUG 2 (roles): applied');
} else {
  console.log('BUG 2 (roles): pattern NOT FOUND in file');
}

fs.writeFileSync('D:/1kaifa/grsds/index.html', s, 'utf8');
console.log('Written', s.length, 'bytes');

try {
  let vm = require('vm');
  let ls = s.lastIndexOf('<script>');
  let le = s.lastIndexOf('</script>');
  let js = s.slice(ls+8, le);
  new vm.Script(js);
  console.log('JS: OK');
} catch(e) {
  console.log('JS FAIL:', e.message.substring(0, 100));
}

let opens = (s.match(/<div[\s>]/g) || []).length;
let closes = (s.match(/<\/div>/g) || []).length;
console.log('Div:', opens, closes, 'diff:', opens - closes);
