const fs = require('fs');
let s = fs.readFileSync('D:/1kaifa/grsds/index.html', 'utf8');

// FIX 1
s = s.replace(
  "else if(tab==='workflows'){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');renderWorkflowTemplates();}",
  "else if(tab==='workflows'){(async function(){var wf=document.getElementById('admin-workflows');wf.classList.remove('hidden');subs[12].classList.add('active');if(!allRoles||!allRoles.length||!allDepartments||!allDepartments.length)await loadAdminData();renderWorkflowTemplates();})();}"
);
console.log('FIX1 OK');

// FIX 2
s = s.replace("wfSetAssignee(2,'value',this.value)", "wfSetAssignee('+idx+','value',this.value)");
console.log('FIX2 OK');

// FIX 3 - staff dropdown: find the exact raw bytes and replace
// In the file, the line is generated by JS code:
//   h+='<select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>无</option>';
// We need to fix the HTML attributes that lack quotes: id="..." onchange="..." value="..."
// Also staffId → "staffId"

// Find the exact pattern by looking for it
let staffDropPattern1 = '<select id=wf-staff-dd-';
let spIdx = s.indexOf(staffDropPattern1);
console.log('staff dropdown at:', spIdx);
if (spIdx > 0) {
  // Find the end of this h+='...'; statement
  let lineStart = s.lastIndexOf("h+='", spIdx);
  let lineEnd = s.indexOf("';", spIdx);
  let line = s.slice(lineStart, lineEnd+2);
  console.log('Staff line:', line.substring(0, 200));
  
  // Now replace the problematic parts
  // Old: <select id=wf-staff-dd-'+idx+' onchange=wfSetAssignee('+idx+',staffId,this.value)><option value=>
  // New: <select id="wf-staff-dd-'+idx+'" onchange="wfSetAssignee('+idx+','staffId',this.value)"><option value="">
  
  let oldLinePart = "<select id=wf-staff-dd-'";
  let newLinePart = '<select id="wf-staff-dd-\'';
  s = s.replace(oldLinePart, newLinePart);
  
  // After the '+idx+' part: ' onchange=wfSetAssignee('+idx+',staffId,this.value)>
  // Should be: '" onchange="wfSetAssignee('+idx+','staffId',this.value)">
  let oldLinePart2 = "' onchange=wfSetAssignee('+idx+',staffId,this.value)>";
  let newLinePart2 = "'\" onchange=\"wfSetAssignee('+idx+','staffId',this.value)\">";
  s = s.replace(oldLinePart2, newLinePart2);
  
  // Fix option value: <option value=> → <option value="">
  let oldOpt = "<option value=>";
  let newOpt = '<option value="">';
  s = s.replace(oldOpt, newOpt);
  
  // Fix the closing option: '+escHtml...' → '+escHtml...'
  // Also fix the staff option line which has: h+='<option value='+escHtml(allUsers[ui].user_id)+
  // The value should have quotes: <option value="'
  
  // This is: h+='<option value='+escHtml(allUsers[ui].user_id)+''+
  // The HTML needs: <option value="'    
  let oldOpt2 = "+'<option value='+escHtml(allUsers[ui].user_id)+\"";
  let newOpt2 = "+'<option value=\"'+escHtml(allUsers[ui].user_id)+\"";
  s = s.replace(oldOpt2, newOpt2);
  
  console.log('FIX3 OK');
}

// FIX 4 - GPS
let gps = fs.readFileSync('D:/1kaifa/grsds/_gps_new.txt', 'utf8').trim();
let dc = s.indexOf('async function doCheckIn(type){');
let ov = s.indexOf('\nfunction openVisitForm', dc);
if (dc > 0 && ov > dc) {
  s = s.slice(0, dc) + gps + '\n' + s.slice(ov);
  console.log('FIX4 OK, delta', ov-dc-gps.length);
}

fs.writeFileSync('D:/1kaifa/grsds/index.html', s, 'utf8');

// Verify
let ls = s.lastIndexOf('<script>'), le = s.lastIndexOf('</script>');
try { new (require('vm').Script)(s.slice(ls+8, le)); console.log('JS: OK'); }
catch(e) { 
  console.log('JS FAIL:', e.message.substring(0,200)); 
  // Find error line
  let el = e.stack ? e.stack.match(/:(\d+)/) : (e.message ? e.message.match(/at (\d+)/) : null);
  if (el) {
    let lines = s.slice(ls+8, le).split('\n');
    let ln = parseInt(el[1]);
    for (let k = Math.max(0,ln-3); k < Math.min(lines.length, ln+2); k++)
      console.log('L'+(k+1)+': '+(lines[k]||'').substring(0,150));
  }
}
let o=(s.match(/<div[\s>]/g)||[]).length, c=(s.match(/<\/div>/g)||[]).length;
console.log('Div:', o, c, o-c, 'Size:', s.length);
