-- 补 contacts 表缺失列
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS title TEXT DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS is_decision_maker BOOLEAN DEFAULT false;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS birthday DATE;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS relationship_to TEXT DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
