-- ============================================================
-- 导入重庆信息化相关政府/国企机构到 companies 表
-- 数量: 21 条
-- ============================================================

-- 1. 补充列（幂等）
ALTER TABLE companies ADD COLUMN IF NOT EXISTS contact TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS province TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS business_scope TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS established DATE;

-- 确保 name 唯一约束
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='companies_name_key') THEN ALTER TABLE companies ADD CONSTRAINT companies_name_key UNIQUE (name); END IF; END $$;

INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆市大数据应用发展管理局', '023-67765318', '重庆', '重庆', '[市级主管单位] | 地址:（dsjj.cq.gov.cn） | 网站:http://dsjj.cq.gov.cn/ | 下属数字重庆公司、数字资源集团等；另有下属事业单位及管理企业 | 办公时间:上午9:00-12:00 下午2:00-6:00（法定工作日） | 传真:023-67769748', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆市经济和信息化委员会', '023-63897162', '重庆', '重庆', '[市级主管单位] | 地址:重庆市两江新区云杉南路12号 | 网站:https://jjxxw.cq.gov.cn/ | 下属重庆信息通信研究院（中国信通院西部分院）', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('渝中区大数据应用发展管理局', '023-63845011 / 023-63626365', '重庆', '重庆', '[区县大数据局] | 网站:https://www.cqyz.gov.cn/bm_229/qdsjfzj/ | 24小时电话023-63845011；工作日白天传真023-63841382；节假日传真023-63709558 | 传真:023-63841382 / 023-63626365', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('铜梁区大数据应用发展管理局', '023-45698586', '重庆', '重庆', '[区县大数据局]', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('南川区大数据应用发展管理局', '023-71460770', '重庆', '重庆', '[区县大数据局] | 地址:重庆市南川区隆化大道9号综合服务中心1号楼5楼 | 网站:http://www.cqnc.gov.cn/ | 下属单位：南川区大数据应用发展中心 | 办公时间:周一至周五 8:30-12:30, 14:30-18:00（法定节假日除外）', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('沙坪坝区大数据应用发展管理局', '023-65368907', '重庆', '重庆', '[区县大数据局] | 地址:重庆市沙坪坝区磁器口街道教院路59号 | 网站:https://www.cqspb.gov.cn/bm/qdsjfzj/ | 下属：沙坪坝区数据资源服务中心；局长：朱斌 | 办公时间:周一至周五 9:00-12:30, 14:00-18:00（法定节假日除外）', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('南岸区大数据应用发展管理局', '023-62620612', '重庆', '重庆', '[区县大数据局] | 网站:https://www.cqna.gov.cn/bm/qdsjfzj/ | 办公时间:9:00-12:30, 14:00-18:00（法定节假日、公休日除外）', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('江津区大数据应用发展管理局', '023-47567678', '重庆', '重庆', '[区县大数据局] | 网站:http://www.jiangjin.gov.cn/bm/cqsjjqdsjyyfzglj/ | 下设综合科、数据资源管理科 | 办公时间:周一至周五 9:00-12:30, 14:00-18:00（法定节假日除外）', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆信息通信研究院（中国信通院西部分院）', '023-88069965', '重庆', '重庆', '[研究机构/事业单位] | 地址:重庆市南岸区玉马路8号科创中心C栋1楼 | 网站:https://www.cqcatr.com/ | 2010年由市经信委+南岸区政府+中国信通院三方共建的事业单位；550余人，设备5亿余元，实验/办公5万㎡，30亩新基地在建；设立海外知识产权纠纷应对指导工作站', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆市数字化城市管理中心', NULL, '重庆', '重庆', '[研究机构/事业单位] | 原重庆市市政信息中心，负责数字化城市管理工作', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆市国企信创和网信安全保障中心', NULL, '重庆', '重庆', '[研究机构/事业单位] | 由市地产集团成立', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('数字重庆大数据应用发展有限公司', NULL, '重庆', '重庆', '[数字重庆系—母公司] | 市属重点国有企业 | 地址:重庆市渝北区渝兴广场B1栋17楼 | 网站:https://www.bigdatacq.com/ | 全市唯一市政府授权负责政务数据运营的载体平台；2025年8月重组为数字重庆大数据集团有限公司（数字重庆集团）', '2019-07-01', 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('数字重庆政务科技有限公司', NULL, '重庆', '重庆', '[数字重庆系—控股子公司] | 数字重庆控股 | 地址:同母公司体系 | 运营''渝快办''；构建''2+N''产品矩阵（城市级数字底座+城市级操作系统），面向全国', '2022-07-01', 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆渝数科技有限公司', NULL, '重庆', '重庆', '[数字重庆系—控股子公司] | 数字重庆+九龙坡区合资 | 聚焦数字政务建设、企业数字化转型，城市服务平台、企业赋能平台', '2023-03-01', 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('西部数据交易有限公司（西部数据交易中心）', '王经理 17702340105 / 余经理 18580868701 / 潘经理 15025469950', '重庆', '重庆', '[数字重庆系—控股子公司] | 地址:重庆市江北区科技金融中心3号楼5-6层（4000㎡） | 网站:https://www.westdex.com.cn/ | 国家发改委+中央网信办等部委及重庆市政府共同批准成立；数据产品超5000款，数商超500家，交易额超6亿；2026年6月上线渝中专区 | 邮箱:wangyanchun@westdex.com.cn / yuhua@westdex.com.cn', '2021-12-01', 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆征信有限责任公司', NULL, '重庆', '重庆', '[数字重庆系—参股] | 数字重庆参股', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('中科曙光（重庆）公司', NULL, '重庆', '重庆', '[数字重庆系—参股] | 数字重庆参股', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('数字涪陵公司', NULL, '重庆', '重庆', '[数字重庆系—参股] | 数字重庆参股', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('西部车网（重庆）有限公司', NULL, '重庆', '重庆', '[数字重庆系—参股] | 数字重庆参股', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆数字资源集团有限公司', NULL, '重庆', '重庆', '[数字资源集团] | 网站:https://www.bigdatacq.com/ | 负责一体化数字资源系统、公共数据资源管理系统、''渝快政''；旗下有智算科技分公司', NULL, 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;
INSERT INTO companies (name, contact, city, province, business_scope, established, status) VALUES ('重庆智算科技有限公司（智算科技分公司）', NULL, '重庆', '重庆', '[数字资源集团] | 运营重庆人工智能创新中心；原为独立公司，后转数字重庆公司下属智算科技分公司，现属数字资源集团', '2023-01-01', 'approved') ON CONFLICT (name) DO UPDATE SET contact=EXCLUDED.contact, business_scope=EXCLUDED.business_scope, established=EXCLUDED.established;

-- 验证
SELECT count(*) AS imported FROM companies WHERE province='重庆' AND city='重庆';
