-- ============================================================
-- CRM 报表与BI分析模块 — 数据库升级
-- 创建自定义仪表盘表 + RLS策略
-- ============================================================

CREATE TABLE IF NOT EXISTS custom_dashboards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '我的仪表盘',
  layout JSONB NOT NULL DEFAULT '[]',
  scope TEXT NOT NULL DEFAULT 'personal' CHECK (scope IN ('personal','role','company')),
  role_filter TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 开启行级安全
ALTER TABLE custom_dashboards ENABLE ROW LEVEL SECURITY;

-- 策略1：所有登录用户可查看公司级仪表盘
CREATE POLICY "Company members view dashboards" ON custom_dashboards
  FOR SELECT
  USING (
    company_id IN (SELECT company_id FROM profiles WHERE user_id = auth.uid())
    OR EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'super_admin')
  );

-- 策略2：用户可CRUD自己的仪表盘
CREATE POLICY "Users manage own dashboards" ON custom_dashboards
  FOR ALL
  USING (user_id = auth.uid());

-- 策略3：超管全权管理所有仪表盘
CREATE POLICY "Super admin manages all dashboards" ON custom_dashboards
  FOR ALL
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'super_admin')
  );

-- 索引建议
CREATE INDEX IF NOT EXISTS idx_custom_dashboards_company ON custom_dashboards(company_id);
CREATE INDEX IF NOT EXISTS idx_custom_dashboards_user ON custom_dashboards(user_id);
CREATE INDEX IF NOT EXISTS idx_custom_dashboards_scope ON custom_dashboards(scope);
