-- 更新标准销售流程模板的步骤权限
-- 定义：销售、售前、售后、采购、财务 各部门的可见和可编辑权限

UPDATE workflow_templates 
SET steps = '[
  {"seq":1,"phase":"线索","key":"gather","name":"搜集线索","icon":"🔍","panel":"lead_gathering","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":2,"phase":"商机","key":"analyze","name":"分析与验证","icon":"💡","panel":"analysis","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":3,"phase":"分析与策略","key":"competitors","name":"获取竞争对手名单","icon":"📋","panel":"competitor","tip":"从客户库搜索添加","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":4,"phase":"分析与策略","key":"compete_analysis","name":"竞争与分析","icon":"📊","panel":"competitor","tip":"填写竞争分析笔记","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":5,"phase":"分析与策略","key":"decision_join","name":"参与决策","icon":"🚦","decision":true,"decisionAsk":"是否参与决策？","decisionYes":"6","decisionNo":"46","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":6,"phase":"内部赋能","key":"training","name":"学习培训","icon":"📚","panel":"training","tip":"培训管理与记录","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":7,"phase":"内部赋能","key":"product_training","name":"产品培训","icon":"🎓","panel":"training","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":8,"phase":"内部赋能","key":"solution_training","name":"方案培训","icon":"📝","panel":"training","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":9,"phase":"内部赋能","key":"training_check","name":"培训考核","icon":"✅","decision":true,"decisionAsk":"培训是否通过？","decisionYes":"10","decisionNo":"6","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":10,"phase":"方案交流","key":"first_contact","name":"初次接洽","icon":"🤝","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":11,"phase":"方案交流","key":"need_mining","name":"需求挖掘","icon":"⛏️","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":12,"phase":"方案交流","key":"tech_exchange","name":"技术交流","icon":"🔬","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":13,"phase":"方案交流","key":"solution_design","name":"方案设计","icon":"📐","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":14,"phase":"方案交流","key":"solution_review","name":"方案评审","icon":"👀","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":15,"phase":"方案交流","key":"solution_present","name":"方案汇报","icon":"🎤","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":16,"phase":"方案交流","key":"solution_confirm","name":"方案确认","icon":"✔️","panel":"communication","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":17,"phase":"招投标","key":"bid_check","name":"投标资格确认","icon":"🔖","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":18,"phase":"招投标","key":"bid_doc_buy","name":"购买标书","icon":"💰","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":19,"phase":"招投标","key":"bid_prepare","name":"标书编制","icon":"📄","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":20,"phase":"招投标","key":"bid_review","name":"标书审核","icon":"🔍","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","admin"]},
  {"seq":21,"phase":"招投标","key":"bid_seal","name":"封装盖章","icon":"🖊️","panel":"bidding","block_visible_to":["销售","售前","售后","采购","admin"],"block_editable_to":["采购","admin"]},
  {"seq":22,"phase":"招投标","key":"bid_submit","name":"投标","icon":"📬","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":23,"phase":"招投标","key":"bid_open","name":"开标","icon":"🎯","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":24,"phase":"招投标","key":"bid_eval","name":"评标","icon":"⚖️","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","售前","admin"]},
  {"seq":25,"phase":"招投标","key":"bid_result","name":"中标通知","icon":"🏆","panel":"bidding","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":26,"phase":"招投标","key":"bid_fail","name":"未中标处理","icon":"🔄","panel":"bidding","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":27,"phase":"合同签订","key":"contract_prepare","name":"合同准备","icon":"📋","panel":"contract","decision":true,"decisionAsk":"是否有提前施工函？","decisionYes":"42","decisionNo":"28","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":28,"phase":"合同签订","key":"contract_draft","name":"合同草拟","icon":"✍️","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":29,"phase":"合同签订","key":"contract_price","name":"价格谈判","icon":"💬","panel":"contract","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["销售","admin"]},
  {"seq":30,"phase":"合同签订","key":"contract_terms","name":"条款谈判","icon":"📑","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":31,"phase":"合同签订","key":"contract_tech","name":"技术协议","icon":"🔧","panel":"contract","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售前","售后","admin"]},
  {"seq":32,"phase":"合同签订","key":"contract_dept","name":"部门会签","icon":"👥","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","售前","售后","采购","admin"]},
  {"seq":33,"phase":"合同签订","key":"contract_legal","name":"法务审核","icon":"⚖️","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["admin"]},
  {"seq":34,"phase":"合同签订","key":"contract_finance","name":"财务审核","icon":"💵","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["财务","admin"]},
  {"seq":35,"phase":"合同签订","key":"contract_final","name":"终稿确认","icon":"✅","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":36,"phase":"合同签订","key":"contract_ceo","name":"总经理审批","icon":"👤","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["admin"]},
  {"seq":37,"phase":"合同签订","key":"contract_sign","name":"合同签署","icon":"🖊️","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":38,"phase":"合同签订","key":"contract_seal","name":"盖章","icon":"🔴","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["采购","admin"]},
  {"seq":39,"phase":"合同签订","key":"contract_archive","name":"合同归档","icon":"📁","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":40,"phase":"合同签订","key":"contract_legal2","name":"法务审核","icon":"⚖️","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["admin"]},
  {"seq":41,"phase":"合同签订","key":"sign_seal","name":"签章","icon":"🖊️","panel":"contract","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["销售","admin"]},
  {"seq":42,"phase":"交付","key":"schedule_ctrl","name":"工期把控","icon":"⏱️","panel":"delivery","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售后","admin"]},
  {"seq":43,"phase":"交付","key":"eng_docs","name":"工程文档","icon":"📁","panel":"delivery","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售后","admin"]},
  {"seq":44,"phase":"交付","key":"sign_material","name":"签收材料","icon":"📦","panel":"delivery","block_visible_to":["销售","售前","售后","admin"],"block_editable_to":["售后","admin"]},
  {"seq":45,"phase":"开票回款","key":"invoice_collect","name":"开票回款","icon":"💵","panel":"payment","block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["财务","admin"]},
  {"seq":46,"phase":"结束","key":"end","name":"结束","icon":"⏹️","end":true,"block_visible_to":["销售","售前","售后","采购","财务","admin"],"block_editable_to":["admin"]}
]'::jsonb
WHERE name = '标准销售流程';
