-- 产品库存管理系统
-- 产品分类
CREATE TABLE IF NOT EXISTS product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  description TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE product_categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_cat_select" ON product_categories;
CREATE POLICY "company_cat_select" ON product_categories FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_cat_insert" ON product_categories;
CREATE POLICY "company_cat_insert" ON product_categories FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_cat_update" ON product_categories;
CREATE POLICY "company_cat_update" ON product_categories FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_cat_delete" ON product_categories;
CREATE POLICY "company_cat_delete" ON product_categories FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 产品档案
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  category_id BIGINT,
  name TEXT NOT NULL,
  code TEXT DEFAULT '',
  specs JSONB DEFAULT '{}',
  images JSONB DEFAULT '[]',
  cost_price NUMERIC(12,2) DEFAULT 0,
  selling_price NUMERIC(12,2) DEFAULT 0,
  unit TEXT DEFAULT '个',
  description TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_prod_select" ON products;
CREATE POLICY "company_prod_select" ON products FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_prod_insert" ON products;
CREATE POLICY "company_prod_insert" ON products FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_prod_update" ON products;
CREATE POLICY "company_prod_update" ON products FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_prod_delete" ON products;
CREATE POLICY "company_prod_delete" ON products FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 仓库
CREATE TABLE IF NOT EXISTS warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  address TEXT DEFAULT '',
  description TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_wh_select" ON warehouses;
CREATE POLICY "company_wh_select" ON warehouses FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_wh_insert" ON warehouses;
CREATE POLICY "company_wh_insert" ON warehouses FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_wh_update" ON warehouses;
CREATE POLICY "company_wh_update" ON warehouses FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_wh_delete" ON warehouses;
CREATE POLICY "company_wh_delete" ON warehouses FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 出入库记录（台账）
CREATE TABLE IF NOT EXISTS stock_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  type TEXT NOT NULL CHECK(type IN('in','out')),
  quantity NUMERIC(12,2) NOT NULL,
  unit_price NUMERIC(12,2) DEFAULT 0,
  total_amount NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
  stock_balance NUMERIC(12,2) DEFAULT 0,
  batch_no TEXT DEFAULT '',
  remark TEXT DEFAULT '',
  recorded_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE stock_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_sr_select" ON stock_records;
CREATE POLICY "company_sr_select" ON stock_records FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sr_insert" ON stock_records;
CREATE POLICY "company_sr_insert" ON stock_records FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()) AND recorded_by=auth.uid());
DROP POLICY IF EXISTS "company_sr_update" ON stock_records;
CREATE POLICY "company_sr_update" ON stock_records FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sr_delete" ON stock_records;
CREATE POLICY "company_sr_delete" ON stock_records FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 库存预警设置
CREATE TABLE IF NOT EXISTS stock_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  warehouse_id BIGINT,
  min_stock NUMERIC(12,2) DEFAULT 0,
  max_stock NUMERIC(12,2) DEFAULT 0,
  enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE stock_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_sa_select" ON stock_alerts;
CREATE POLICY "company_sa_select" ON stock_alerts FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sa_insert" ON stock_alerts;
CREATE POLICY "company_sa_insert" ON stock_alerts FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sa_update" ON stock_alerts;
CREATE POLICY "company_sa_update" ON stock_alerts FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sa_delete" ON stock_alerts;
CREATE POLICY "company_sa_delete" ON stock_alerts FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 盘点记录
CREATE TABLE IF NOT EXISTS stock_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  warehouse_id BIGINT NOT NULL,
  check_date DATE DEFAULT current_date,
  checked_by UUID REFERENCES auth.users(id),
  status TEXT DEFAULT 'draft' CHECK(status IN('draft','done','cancelled')),
  remark TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE stock_checks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "company_sc_select" ON stock_checks;
CREATE POLICY "company_sc_select" ON stock_checks FOR SELECT USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sc_insert" ON stock_checks;
CREATE POLICY "company_sc_insert" ON stock_checks FOR INSERT WITH CHECK (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sc_update" ON stock_checks;
CREATE POLICY "company_sc_update" ON stock_checks FOR UPDATE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));
DROP POLICY IF EXISTS "company_sc_delete" ON stock_checks;
CREATE POLICY "company_sc_delete" ON stock_checks FOR DELETE USING (company_id=(SELECT company_id FROM public.profiles WHERE user_id=auth.uid()));

-- 盘点明细
CREATE TABLE IF NOT EXISTS stock_check_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_id BIGINT NOT NULL REFERENCES stock_checks(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL,
  book_qty NUMERIC(12,2) DEFAULT 0,
  actual_qty NUMERIC(12,2) DEFAULT 0,
  diff_qty NUMERIC(12,2) GENERATED ALWAYS AS (actual_qty - book_qty) STORED,
  remark TEXT DEFAULT ''
);
ALTER TABLE stock_check_items ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_stock_records_product ON stock_records(product_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_warehouse ON stock_records(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_records_type ON stock_records(type);
CREATE INDEX IF NOT EXISTS idx_stock_records_created ON stock_records(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_stock_alerts_product ON stock_alerts(product_id);

-- 当前库存视图
DROP VIEW IF EXISTS v_current_stock;
CREATE VIEW v_current_stock AS
SELECT 
  sr.product_id,
  sr.warehouse_id,
  sr.company_id,
  SUM(CASE WHEN sr.type='in' THEN sr.quantity ELSE -sr.quantity END) AS balance
FROM stock_records sr
GROUP BY sr.product_id, sr.warehouse_id, sr.company_id;

NOTIFY pgrst, 'reload schema';